name: Eslint-check

on:
  push:
    branches:
      - main 

jobs:
  Eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Eslint checking
        run: npx eslint .